# Generated by Django 4.1 on 2022-08-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField(max_length=50)),
                ('lte_exist', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
    ]
