# Generated by Django 4.1 on 2022-08-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phones_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='lte_exist',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='phones',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='phones',
            name='price',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='phones',
            name='release_date',
            field=models.DateTimeField(max_length=150),
        ),
    ]
